/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}", "./utils/**/*.{js,ts,jsx,tsx}"],
  plugins: [require("daisyui")],
  darkTheme: "dark",
  darkMode: ["selector", "[data-theme='dark']"],
  daisyui: {
    themes: [
      {
        light: {
          primary: "#0D1B2A",
          "primary-content": "#E0E1DD",
          secondary: "#1B263B",
          "secondary-content": "#E0E1DD",
          accent: "#415A77",
          "accent-content": "#E0E1DD",
          neutral: "#778DA9",
          "neutral-content": "#0D1B2A",
          "base-100": "#E0E1DD",
          "base-200": "#F4F4F4",
          "base-300": "#C5C6C7",
          "base-content": "#0D1B2A",
          info: "#00A8E8",
          success: "#34EEB6",
          warning: "#FFCF72",
          error: "#FF8863",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
      {
        dark: {
          primary: "#E0E1DD",
          "primary-content": "#0D1B2A",
          secondary: "#778DA9",
          "secondary-content": "#0D1B2A",
          accent: "#415A77",
          "accent-content": "#0D1B2A",
          neutral: "#1B263B",
          "neutral-content": "#E0E1DD",
          "base-100": "#0D1B2A",
          "base-200": "#1B263B",
          "base-300": "#415A77",
          "base-content": "#E0E1DD",
          info: "#00A8E8",
          success: "#34EEB6",
          warning: "#FFCF72",
          error: "#FF8863",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px", "--tooltip-color": "oklch(var(--p))" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
    ],
  },
  theme: {
    extend: {
      boxShadow: { center: "0 0 12px -2px rgb(0 0 0 / 0.05)" },
      animation: { "pulse-fast": "pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite" },
      colors: {
        background: "#E0E1DD",
        foreground: "#0D1B2A",
      },
    },
  },
};
